version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: localhost
      MYSQL_DATABASE: solar_energy_db
      MYSQL_USER: root
      MYSQL_PASSWORD: localhost
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
